name: MCEngineCurrency
version: ${version}
main: io.github.mcengine.spigotmc.currency.engine.MCEngineCurrencySpigotMC
author: MCEngine
description: MCEngine Currency
api-version: 1.13
commands:
  currency:
    description: Manage and check currency balances.
    usage: /currency check <coinType> | /currency check <player> <coinType> | /currency add <player> <coinType> <amount>
    permission: mcengine.currency
    permission-message: You do not have permission to use this command.