name: MCEngineEconomy
version: ${version}
main: io.github.mcengine.papermc.economy.engine.MCEngineEconomyPaperMC
author: MCEngine
description: MCEngine Economy
api-version: 1.13
commands:
  economy:
    description: Manage and check economy balances.
    usage: /economy check <coinType> | /economy check <player> <coinType> | /economy add <player> <coinType> <amount>
    permission: mcengine.economy
    permission-message: You do not have permission to use this command.
